name: 'dlnerds_store'
version: '1.0.0'

profile: 'dlnerds_store'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  sales_start_date: '2020-01-01'

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  dlnerds_store:
    +schema: 01_bronze

models:
  dlnerds_store:
    01_bronze:
      +enabled: true
      +materialized: table
      +schema: 01_bronze
      +tags: ['bronze']
      +docs:
        node_color: '#CD7F32'
    02_silver:
      +enabled: true
      +materialized: table
      +schema: 02_silver
      +tags: ['silver']
      +docs:
        node_color: 'silver'
    03_gold:
      +enabled: true
      +materialized: table
      +schema: 03_gold
      +tags: ['silgoldver']
      +docs:
        node_color: 'gold'